# agent-integrations-next.yaml is intended to be used with
# docker-compose.integrations-next.yaml. It demonstrates a config with
# --enable-features=integrations-next and --config.expand-env, but does not
# test absolutely all integrations.
server:
  log_level: info
  http_listen_port: 12341

metrics:
  global:
    external_labels:
      origin_prometheus: yearn-exporter-apy
    scrape_interval: 15s
    remote_write:
    - url: ${REMOTE_WRITE}
      basic_auth:
        username: ${REMOTE_WRITE_USERNAME}
        password: ${REMOTE_WRITE_PASSWORD}

integrations:
  node_exporter:
    enabled: true
    rootfs_path: /
    sysfs_path: /sys
    procfs_path: /proc
